### ISSUE TITLE
Incorrect forward mode gradient for truncated normal distribution

### ISSUE THREAD

**Issue by mhauru** [EnzymeAD/Enzyme.jl#1998]
MWE:
```julia
julia> import FiniteDifferences, Enzyme; using Distributions

julia> func = (a, b, x) -> logpdf(truncated(Normal(), a, b), x)
#29 (generic function with 1 method)

julia> args = (-0.3, 0.3, 0.1)
(-0.3, 0.3, 0.1)

julia> Enzyme.gradient(Enzyme.Forward, Enzyme.Const(func), args...)
(0.6272640800199636, -2.607264080019964, -1.09)

julia> Enzyme.gradient(Enzyme.Reverse, Enzyme.Const(func), args...)
(1.6172640800199638, -1.617264080019964, -0.1)

julia> FiniteDifferences.grad(FiniteDifferences.central_fdm(4, 1), func, args...)
(1.6172640800151292, -1.6172640800193545, -0.0999999999999462)
```
On Enzyme v0.13.11.

**Comment by wsmoses** [comment]
A further reduction of this would be helpful to resolving

**Comment by mhauru** [comment]
Would like to help, but unfortunately I'm too busy right now to find time to minimise further. Open for grabs for anyone to do it.

**Comment by wsmoses** [comment]
@yebai @penelopeysm or @willtebbutt would you have cycles to minimize this?

**Comment by wsmoses** [comment]
no one has experience with distributions.jl

if you want it to work, you're going to have to meet us halfway

**Comment by penelopeysm** [comment]
```julia
import Enzyme
import FiniteDifferences
using SpecialFunctions: erfc

function g(s, _not_used)
    k = sin(sin(sin(-erfc(0.25)/2)))
    return (s, k)
end

function f(_not_used)
    t = g((0.0, 3.9555), _not_used)
    return t[1][2]
end

args = (0.0,)

Enzyme.gradient(Enzyme.Forward, Enzyme.Const(f), args...)                 # (3.9555,)
FiniteDifferences.grad(FiniteDifferences.central_fdm(4, 1), f, args...)   # (4.312107145607921e-14,)
```

This is the 'simplest' repro I can get, in that if you make any of the following further simplifications, Enzyme will give the right answer:

1. Reducing the tuple to contain only one element. In fact, this bug only happens if `f` returns `t[1][n]` for `n > 1`.
1. Changing `t[1][1]` to anything but 0. 
1. Unwrapping any of the tuples.
1. Inlining `g` into `f`.
1. Removing literally anything from the definition of `k`, even the division by 2, or the minus sign before `erfc`. (You can change the `sin` to `cos` or any other trig function, but you can't remove any of them.)

Perhaps of interest, the gradient that Enzyme reports back is always the value of `t[1][2]` (illustrated here with `3.9555`.)

**Comment by wsmoses** [comment]
Perfect, that should be enough!

Thanks @penelopeysm !!

**Comment by wsmoses** [comment]
will be fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/2052 pending jll bump
