### ISSUE TITLE
Obtain gradient function using Enzyme.jl

### ISSUE THREAD

**Issue by kirimaru-jp** [EnzymeAD/Enzyme.jl#357]
I would like to use `Enzyme.jl` (version 0.10.0, Julia 1.7.1) to obtain the gradient function.

Following your example [here](https://enzyme.mit.edu/julia/api/#Enzyme.autodiff-Union%7BTuple%7BA%7D,%20Tuple%7BF%7D,%20Tuple%7BEnzyme.ReverseMode,%20F,%20Type%7BA%7D,%20Vararg%7BAny%7D%7D%7D%20where%20%7BF,%20A%3C:Enzyme.Annotation%7D):

`a = 4.2`
`b = [2.2, 3.3]; ∂f_∂b = zero(b)`
`c = 55; d = 9`
`f(a, b, c, d) = a * √(b[1]^2 + b[2]^2) + c^2 * d^2`
`autodiff(Reverse, f, Active, a, Duplicated(b, ∂f_∂b), c, d)`
> 2-element Vector{Float64}:
> 1.1094003924504583
> 1.6641005886756872`

Using `Zygote`, I can obtain the gradient function `g(x) := (∂f/∂b)(x)`
`import Zygote: gradient as Z_grad`
`fx = (x -> f(a,x,c,d))`
`fx(b)`
> 245032.93221280602

`g(x) = Z_grad(fx, x)[1]`
`g(b)`
> 2-element Vector{Float64}:
>  1.1094003924504583
>  1.6641005886756872

`g([1,2])`
> 2-element Vector{Float64}:
>  0.8944271909999159
>  1.7888543819998317

I am trying to do the same with `Enzyme`, but it did not work.
`fill!(∂f_∂b, 0.0)`
`G(x) = Enzyme.autodiff(Reverse, fx, Active, x)`
`G(b)`

`∂f_∂b`
> 2-element Vector{Float64}:
>  0.0
>  0.0

How should I do that using `Enzyme.jl`?

**Comment by wsmoses** [comment]
Hi @kirimaru-jp, the issue here is that you need to mark the variable you want to differentiate wrt as Duplicated (e.g. that you want the derivative wrt it. Without an annotation the `x` you pass to autodiff is assumed to be constant).

```julia
julia> G(x) = Enzyme.autodiff(Reverse, fx, Active, Duplicated(x, ∂f_∂b))
julia> G(b)
()

julia> ∂f_∂b
2-element Vector{Float64}:
 2.3297408241459623
 3.4946112362189434
```

Also for performance reasons, the closure fx you create isn't great because it is type instable (i.e. the captured a, c, d may be of any type). You can fix this by saying:
```
const a = 4.2
const c = 55
const d = 9
```
