### ISSUE TITLE
Sparse Array Structure Initializer

### ISSUE THREAD

**Issue by ryanstoner1** [EnzymeAD/Enzyme.jl#373]
Enzyme sometimes incorrectly returns zeros for sparse arrays.

`using Enzyme
a=sparse([2.0]);
da=sparse([0.0]);
f(a)=sum(a);
Enzyme.autodiff(Reverse,f,Const,Duplicated(a,da))`

Returns da as a sparse array with 0 entries, but as per the Slack suggestion`da=sparse([0.0001])` returns the correct answer (-0.001 also returns the right answer). 

I also tried mixing the two: 

`a=sparse([2.0,1.0]);
da=sparse([0.01,0.0]);
f(a)=sum(a);
Enzyme.autodiff(Reverse,f,Active,Duplicated(a,da))`

This returns the right answer for the first element, and the wrong one for the second element.

`2-element SparseVector{Float64, Int64} with 1 stored entry:
  [1]  =  1.01`

**Comment by Wimmerer** [comment]
The problem here is that SparseMatrixCSC drops explicit zeros right?

**Comment by wsmoses** [comment]
Yeah, in this regard we'd want a version that keeps the non-zero values from the sparse array being zero'd in the backing array (but set to 0).

**Comment by wsmoses** [comment]
Copying my comment from slack here to preserve it:

The same structure constraint for sparsity is a bit more rigorous because specifically the data layout itself between the two should match. Since usually sparse will not actually store the 0 you'll have say an array of size 1 as the backing for a but here for da I can see an array of size 0 as the backing since the 0 will be canonilcaized out. The structure requirement means you also need an array of size 1 as the backing for da so the same constructor as the primal value may not be appropriate (my guess for the 0.001 is a potential hack that I hope also generated the same structure, the proper solution would be to have a structure preserving zero initialized for the sparse)

**Comment by wsmoses** [comment]
Another option here, could be to define custom rules for sparse get/set -- obviating the need for this here.

**Comment by Wimmerer** [comment]
In what function? Constructors?

**Comment by ryanstoner1** [comment]
Like you say, it may be more of an issue with SparseMatrixCSC. @Wimmerer

**Comment by wsmoses** [comment]
We now have such a utility in Enzyme.make_zero
