### ISSUE TITLE
Enzyme 0.11.1 segfaults

### ISSUE THREAD

**Issue by ChrisRackauckas** [EnzymeAD/Enzyme.jl#779]
```julia
using SciMLSensitivity, OrdinaryDiffEq, Zygote

function fiip(du, u, p, t)
    du[1] = dx = p[1] * u[1] - p[2] * u[1] * u[2]
    du[2] = dy = -p[3] * u[2] + p[4] * u[1] * u[2]
end
p = [1.5, 1.0, 3.0, 1.0];
u0 = [1.0; 1.0];
prob = ODEProblem(fiip, complex(u0), (0.0, 10.0), complex(p))

function sum_of_solution(u0, p)
    _prob = remake(prob, u0 = u0, p = p)
    real(sum(solve(_prob, Tsit5(), reltol = 1e-6, abstol = 1e-6, saveat = 0.1, sensealg = InterpolatingAdjoint(autojacvec=EnzymeVJP()))))
end

dx = Zygote.gradient(sum_of_solution, complex(u0), complex(p))
```

segfaults on v0.11.1 but is fine with 0.11. It's doing a vjp calculation of

```julia
function fiip(du, u, p, t)
    du[1] = dx = p[1] * u[1] - p[2] * u[1] * u[2]
    du[2] = dy = -p[3] * u[2] + p[4] * u[1] * u[2]
end
```

**Comment by ChrisRackauckas** [comment]
Isolated:

```julia
using Enzyme

function f(du, u, p, t)
    du[1] = dx = p[1] * u[1] - p[2] * u[1] * u[2]
    du[2] = dy = -p[3] * u[2] + p[4] * u[1] * u[2]
    nothing
end
(tmp3, tmp4, y, tmp1, dup, t) = (ComplexF64[0.0 + 0.0im, 0.0 + 0.0im], ComplexF64[100.0 + 0.0im, 100.0 + 0.0im], ComplexF64[1.0 + 0.0im, 1.0 + 0.0im], ComplexF64[0.0 + 0.0im, 0.0 + 0.0im], Enzyme.Duplicated{Vector{ComplexF64}}(ComplexF64[1.5 + 0.0im, 1.0 + 0.0im, 3.0 + 0.0im, 1.0 + 0.0im], ComplexF64[0.0 + 0.0im, 0.0 + 0.0im, 0.0 + 0.0im, 0.0 + 0.0im]), 0.0)

f2 = function (out, u, _p, t)
       fiip(out, u, _p, t)
       nothing
end

Enzyme.autodiff(Enzyme.Reverse, f2, Enzyme.Duplicated(tmp3, tmp4),
                     Enzyme.DuplicatedNoNeed(y, tmp1),
                     dup,
                     Enzyme.Const(t))
```

**Comment by ChrisRackauckas** [comment]
It requires both the complex numbers and the anonymous function. See:

```julia
using Enzyme

function fiip(du, u, p, t)
    du[1] = dx = p[1] * u[1] - p[2] * u[1] * u[2]
    du[2] = dy = -p[3] * u[2] + p[4] * u[1] * u[2]
    nothing
end
p = [1.5, 1.0, 3.0, 1.0];
u0 = [1.0; 1.0];
du0 = similar(u0)
d_du0 = similar(du0)
d_u0 = similar(u0)
d_p = similar(p)
t = 0.0

f2 = function (out, u, _p, t)
       fiip(out, u, _p, t)
       nothing
end

Enzyme.autodiff(Enzyme.Reverse, f2, Enzyme.Duplicated(du0, d_du0),
                     Enzyme.DuplicatedNoNeed(u0, d_u0),
                     p,
                     Enzyme.Const(t))

p = complex([1.5, 1.0, 3.0, 1.0]);
u0 = complex([1.0; 1.0]);
du0 = similar(u0)
d_du0 = similar(du0)
d_u0 = similar(u0)
d_p = similar(p)
t = 0.0

Enzyme.autodiff(Enzyme.Reverse, fiip, Enzyme.Duplicated(du0, d_du0),
                     Enzyme.DuplicatedNoNeed(u0, d_u0),
                     p,
                     Enzyme.Const(t))

Enzyme.autodiff(Enzyme.Reverse, f2, Enzyme.Duplicated(du0, d_du0),
                     Enzyme.DuplicatedNoNeed(u0, d_u0),
                     p,
                     Enzyme.Const(t))
```

Either one in isolation is fine, but the mixture segfaults.

**Comment by Vaibhavdixit02** [comment]
I have also seen this crop up for hessian calculation in Optimization.jl which was fine on 0.11.0, can provide a MWE if needed

**Comment by ChrisRackauckas** [comment]
We just restricted the patch for now so @wsmoses can do his thesis defense 😅 https://github.com/SciML/SciMLSensitivity.jl/pull/820 . v0.11.0 is fine so it's not too urgent. Optimization.jl and other packages should probably just do the same until this is figured out.

**Comment by wsmoses** [comment]
@ChrisRackauckas this is slight internal semantics change or rather using the DuplicatedNoNeed for optimization. 

Basically the error here is that the forward pass needs to read u, but you mark it as duplicatednoneed.

**Comment by wsmoses** [comment]
@Vaibhavdixit02 yes please open what you see as a separate issue.

**Comment by ChrisRackauckas** [comment]
> Like [Duplicated](https://enzymead.github.io/Enzyme.jl/dev/api/#EnzymeCore.Duplicated), except also specifies that Enzyme may avoid computing the original result and only compute the derivative values.

I read this as `u0` cannot be mutated, and it's not?

**Comment by wsmoses** [comment]
Semantics are still in flux, but this should now be fixed on main.

**Comment by ChrisRackauckas** [comment]
I don't understand. So am I misusing DuplicatedNoNeed and the docstring needs an update or is this fixed by the JLL bump?

**Comment by wsmoses** [comment]
The jll bump should allow this to pass. However, I do think you are misusing it at the moment (and yeah we should update the docs, though noneed itself is still going through a bit of a flux atm).

The intention behind it is as follows: When differentiating a function, the user may not need the output of the function itself and only the derivative.
* For a value returned this is obvious that it would just not be evaluated (and we can dead code eliminate anything going into it that isn't needed elsewhere). 
* For a value stored in memory is where DuplicatedNoNeed comes in. It represents the fact that you permit Enzyme to eliminate stores into memory (and any computations that would create the value stored, if not needed otherwise for the derivative). It does _not_ represent the fact that the memory is read-only (which is what it appears to be what you use it as). Any reads of the memory after the eliminated stores are undefined. The semantics update we are playing with at the moment  is saying that any reads of the memory are undefined (since read-only variables offer no benefit from Duplicated), and read-write variables are presently undefined if done write, read; though permitted presently if read then write.
