### ISSUE TITLE
Incorrect forward-mode result with Const argument

### ISSUE THREAD

**Issue by sethaxen** [EnzymeAD/Enzyme.jl#830]
In this identity function, annotating the sole argument as `Const` and the output type as `Duplicated` should result in the returned derivative being 0, but instead, the derivative is identical to the primal.

```julia
julia> using Enzyme

julia> x = randn(3)
3-element Vector{Float64}:
 -1.4444824325133723
  1.5991479286434434
 -0.519494895032433

julia> autodiff(Forward, x -> x, Duplicated, Const(x))
(var"1" = [-1.4444824325133723, 1.5991479286434434, -0.519494895032433], var"2" = [-1.4444824325133723, 1.5991479286434434, -0.519494895032433])
```

I tried also with `Enzyme.API.runtimeActivity!(true)`, but it had no effect.

**Comment by wsmoses** [comment]
our next jll bump will now give an error for that without runtime activity.

With runtime activity, that is actually currently the expected behavior. Whether that should change is a separate aside.

In essence runtime activity says that we could not statically deduce whether the variable is duplicated or const and as a result all users of the duplicated variable must make the check. The runtime decision is by doing primal === shadow, meaning that it is const, otherwise it is duplicated.

**Comment by sethaxen** [comment]
> Separately there's also an issue about using const memory as a buffer for differentiable values, see https://enzyme.mit.edu/index.fcgi/julia/stable/#Activity-of-temporary-storage

Ah, okay, this perhaps explains the behavior in https://github.com/EnzymeAD/Enzyme.jl/issues/830#issuecomment-1545707189. If I give `Duplicated` for `y` and the return value but `Const` for the remaining arguments, I get the zero vector as expected. Although, if `y` and `x` are matrices, then again the derivative is the same as the primal:

```julia
using Enzyme

function scale!(y, x, a)
    y .= x .* a
    return y
end

# vector args
y = [0.1, -0.2, 0.3]
∂y = zero(y)
x =  [1.0, 2.0, 3.0]
a = 2.5
autodiff(Forward, scale!, Duplicated, Duplicated(y, ∂y), Const(x), Const(a))
# return: (var"1" = [2.5, 5.0, 7.5], var"2" = [0.0, 0.0, 0.0])

# matrix args
y = [0.1 -0.2 0.3]
∂y = zero(y)
x =  [1.0 2.0 3.0]
autodiff(Forward, scale!, Duplicated, Duplicated(y, ∂y), Const(x), Const(a))
# return: (var"1" = [2.5 5.0 7.5], var"2" = [2.5 5.0 7.5])
```

> More docs definitely welcome!

Happy to contribute some once I understand what's intended and what might be a bug!

**Comment by wsmoses** [comment]
Your last one indeed is an error where I accidentally changed the throw illegal error to false always (fixed here): https://github.com/EnzymeAD/Enzyme.jl/pull/838

The behavior of the primal === shadow, only will occur with runtime activity on, and it would specify that whatever variable  where this occurs really is a constant (be it a return, even input to custom rule, etc). Though perhaps with runtime activity on we should do the check on the Enzyme side for custom rules, rather than have the users perform it.

We have some docs on runtime activity here: https://enzymead.github.io/Enzyme.jl/dev/api/#Enzyme.API.runtimeActivity!-Tuple{Bool}

We should probably add to that the comment that we've added throwing in most cases of potential runtime activity (haven't for memcpy, or some of the internal custom rules). However, many of these throws are actually false positives, but turning on runtime activity is always legal (albeit slightly slower, and comes with the Duplicated(x, dx) where x === dx  should be interpreted as Const(x) ).
