### ISSUE TITLE
Clarification on mutable objects

### ISSUE THREAD

**Issue by leonardogalliano** [EnzymeAD/Enzyme.jl#869]
Hi everyone

I am new to automatic differentiation. I decided to use Enzyme since I need to handle mutating objects (even if I am *not* differentiating with respect to these objects).

I try to write a minimal, self-consistent, example:

```
using Enzyme

mutable struct my_struct
    p1::Vector{Float64}
    p2::Float64
end

function edit_str!(str::my_struct, x, i)
    str.p2 = str.p2 + 2x^2
    return nothing
end

function foo(x, str)
    edit_str!(str, x, 1)
    return str.p2
end

str = my_struct([2.0, 3.0], 1.0)

foo(1.0, str), autodiff(Reverse, foo, Active, Active(1.0), str)
```

Here I try to differentiate the function `foo` in `x = 1.0`. Note that the function `edit_str!` inside `foo` changes the object `str`. Yet, I do not need to differentiate with respect to `str`.

I found out that, depending on the mutations on `str`, the code may or may not work. In the above example it gives the right result `4.0`, but if I change it slightly

```
function edit_str!(str::my_struct, x, i)
    str.p1 = str.p1 .+ 1.0
    str.p2 = str.p2 + 2x^2
    return nothing
end
```

it does not work anymore and it gives `0.0`. Note that `str.p1` is not needed anywhere. Perhaps even weirder, this works

```
function edit_str!(str::my_struct, x, i)
    str.p1 = 2.0 * str.p1
    str.p2 = str.p2 + 2x^2
    return nothing
end
```

I guess it depends on the kind of mutation on the `mutable struct`, but I would like to know if there is a robust way of dealing with this.

Thanks a lot.

**Comment by wsmoses** [comment]
Yeah essentially if you store active (e.g. differentiable) data into constant memory (such as the struct here), there's some additional complications.

Specifically, since it's stored into constant data, Enzyme can assume that uses of it in that constant data won't impact the derivative -- since its loading/using a constant!

If it acts as a buffer/temporary storage of derivative data, you'll need to mark it as duplicated (see here: https://enzyme.mit.edu/index.fcgi/julia/stable/#Activity-of-temporary-storage). The reason for this is because if you build up some arbitrary data structure, we also need to construct the shadow (aka derivative) data structure. Without the shadow data structure, we have no location as memory to use for the temporary storage of the derivative!

Your first case is actually why I was very careful and said that Enzyme _can_ assume that uses of it won't impact the derivative, rather than Enzyme _will_ assume. The reason in that case, is that the computation was simple enough that an optimization realized it was returning the input variable x and decided to return that directly rather than actually loading from the constant struct. Therefore it is returning an active value, and has a meaningful derivative. If you want guarantee that all uses of a variable will not have their uses change the derivative, we have a construct for that too. In essence it's equivalent to making a custom rule that behaves identity-like, but is marked inactive.
